# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy ASP.Net Core app to Azure Web App - lexicon2025vtdb

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: read # Required for actions/checkout

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.x'

      - name: Restore Dependencies
        run: dotnet restore

      - name: Build with dotnet
        run: dotnet build --configuration Release

      - name: dotnet publish
        run: dotnet publish -c Release -o "${{env.DOTNET_ROOT}}/myapp"

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: .net-app
          path: ${{env.DOTNET_ROOT}}/myapp
          
      - name: Install EntityFrameworkCore Tools
        run: |
          dotnet new tool-manifest
          dotnet tool install dotnet-ef

      - name: Generate EF Core Migration Script
        run: dotnet ef migrations script --idempotent --configuration Release --no-build --output "${{github.workspace}}/sql/sql-script.sql" --context Lexicon2025VTDatabaseDeploy.Data.Lexicon2025VTDatabaseDeployContext --project ${{github.workspace}}/Lexicon2025VTDatabaseDeploy/Lexicon2025VTDatabaseDeploy.csproj

      - uses: actions/upload-artifact@v4
        with:
          name: ddl-updates
          path: ${{github.workspace}}/sql/sql-script.sql

  deploy:
    runs-on: windows-latest
    needs: build
    permissions:
      id-token: write # Required for requesting the JWT
      contents: read # Required for actions/checkout

    steps:
      - name: Download app artifact
        uses: actions/download-artifact@v4
        with:
          name: .net-app
          path: ./.net-app

      - name: Download SQL artifact
        uses: actions/download-artifact@v4
        with:
          name: ddl-updates
          path: ./ddl-updates
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_FCDD4B039BF546E4B3E9D1D3A3142047 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_750251A29FA64327BA454D9CBFF1D306 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_BA64BE3648034A789703D1477E2A22DF }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'lexicon2025vtdb'
          slot-name: 'Production'
          package: ./.net-app/

      - name: Azure SQL Deploy
        uses: Azure/sql-action@v2
        with:
          connection-string: ${{ secrets.SQL_CONNECTION_STRING }}
          path: ./ddl-updates/sql-script.sql
